### ISSUE TITLE
how to divide other onnx model using gillis?

### ISSUE THREAD

**Issue by Chenhait** [MincYu/gillis-open-source#1]
Hi, MincYu.
Thank you for your wonderful work!!!

I try to partition resnet model using gillis.
However, when I run

wget https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet34v2/resnet34v2.onnx
python main.py lo -n resnet34v2.onnx -p true

It comes an error
mxnet.base.MXNetError: MXNetError: Invalid Parameter format for end expect int or None but value='34.0', in operator slice_axis(name="", end="34.0", begin="0.0", axis="2")

I wonder if I use the improper version of onnx model.
could you please offer the onnx model in your code?
Or if any other suggestion

Thank you again
best

**Comment by MincYu** [comment]
Hi Chenhait, 

Thank you for your interests. 

In fact, we generated ResNet models (and their variants) by ourself, and you may find the script here: https://github.com/MincYu/gillis-open-source/blob/main/tool/wresnet_builder.py

We also uploaded a few ResNet variants to S3, which are primarily used in evaluation. For example, you may directly download WResNet-34-3 via https://s3.amazonaws.com/model.onnx/wrn34_3.onnx

Best
